// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starter.DAO;

namespace Starter.Migrations
{
    [DbContext(typeof(StarterDbContext))]
    partial class StarterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Starter.Models.CourseModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProfessorModelid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("atCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("professorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("timeOfDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ProfessorModelid");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("Starter.Models.ProfessorModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("professors");
                });

            modelBuilder.Entity("Starter.Models.CourseModel", b =>
                {
                    b.HasOne("Starter.Models.ProfessorModel", null)
                        .WithMany("currentCourses")
                        .HasForeignKey("ProfessorModelid");
                });
#pragma warning restore 612, 618
        }
    }
}
